/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminSection;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 20122
 */
public class IssueBookFrame extends javax.swing.JFrame {

    DateFormat dateformat = new SimpleDateFormat("MM/dd/YY");
    Date date = new Date() ;
    Calendar cal = Calendar.getInstance();
    
    Book b1[]=new Book[100];
    Student s1[] = new Student[100];
    int count=0;
    int counts=0;
    /**
     * Creates new form IssueBookFrame
     * @throws java.io.FileNotFoundException
     */
    public IssueBookFrame() throws FileNotFoundException {
        initComponents();
        readFilebook();
        readFileStudent();
    }
public void readFilebook() throws FileNotFoundException{
        File f = new File("books.txt");
        Scanner s = new Scanner(f);
        while(s.hasNextLine()){
            String book = s.nextLine();
            String token[]=book.split(",");
                    b1[count]=new Book(token[0],token[1],token[2],token[3],Integer.parseInt(token[4]));
                    count ++;
        }
    }
 public void readFileStudent() throws FileNotFoundException{
        File f = new File("students.txt");
        Scanner s = new Scanner(f);
        while(s.hasNextLine()){
            String student = s.nextLine();
            String token[]=student.split(",");
                   s1[counts] = new Student(token[0],token[1],token[2],token[3],token[4],token[5],token[6],Integer.parseInt(token[7]));
                    counts ++;
        }
    }
 public  void writeFileStudents() throws FileNotFoundException{
     File f=new File("students.txt");
        try (PrintWriter pw = new PrintWriter(f)) {
            int i;
            for(i=0;i<counts;i++){
                pw.println(s1[i].getName()+","+s1[i].getPassword()+","+s1[i].getAddress()+","+s1[i].getPhonenumber()+","+s1[i].getCity()+","+s1[i].getEmail()+","+s1[i].getId()+","+s1[i].getI());
                
            }
            pw.close();
        }
 }
 public void writeFileBooks() throws FileNotFoundException{
     File f=new File("books.txt");
        try (PrintWriter pw = new PrintWriter(f)) {
            int i;
            for(i=0;i<counts;i++){
                pw.println(b1[i].getCallnumber()+","+b1[i].getName()+","+b1[i].getAuthor()+","+b1[i].getPublisher()+","+b1[i].getQuantity());
                
            }
            pw.close();
        }
        
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookCallNumberField = new javax.swing.JTextField();
        studentIdField = new javax.swing.JTextField();
        studentNameField = new javax.swing.JTextField();
        studentContactField = new javax.swing.JTextField();
        DateField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addBooksButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        returnDateField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Issue Book");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Book call number:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Student name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Student contact:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Student ID:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Return date:");

        studentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameFieldActionPerformed(evt);
            }
        });

        studentContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentContactFieldActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addBooksButton.setBackground(new java.awt.Color(0, 255, 0));
        addBooksButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addBooksButton.setForeground(new java.awt.Color(51, 51, 51));
        addBooksButton.setText("Done");
        addBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBooksButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Date:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addBooksButton)
                        .addGap(92, 92, 92)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateField)
                            .addComponent(studentContactField)
                            .addComponent(studentNameField)
                            .addComponent(studentIdField)
                            .addComponent(bookCallNumberField)
                            .addComponent(returnDateField))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookCallNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentContactField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBooksButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameFieldActionPerformed

    private void studentContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentContactFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hide();
        new LibrarianSectionMenuFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBooksButtonActionPerformed
        this.hide();
        boolean failed=true;
        for(int i=0;i<count;i++){
            if(bookCallNumberField.getText().equals(b1[i].getCallnumber())){
                for(int j=0;j<counts;j++){
                    if((studentNameField.getText().equals(s1[j].getName()))&&(studentIdField.getText().equals(s1[j].getId()))&&(studentContactField.getText().equals(s1[j].getPhonenumber()))){
                     if(b1[i].getQuantity()==0)
                         JOptionPane.showMessageDialog(this, "Please check your data", "Invalid information", JOptionPane.ERROR_MESSAGE); 
                     else{
                        IssueBook b=new IssueBook(b1[i],s1[j],DateField.getText(),returnDateField.getText());
                        failed=false;
                        try {
                            b.addToFile();
                        } catch (IOException ex) {
                            Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        s1[j].setI(s1[j].getI()+1);
                        b1[i].setQuantity(b1[i].getQuantity()-1);
                         try {
                             writeFileStudents();
                         } catch (FileNotFoundException ex) {
                             Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
                         }
                         try {
                             writeFileBooks();
                         } catch (FileNotFoundException ex) {
                             Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
                         }
 }
                    }
                }
            }
                
        }
        if(failed){
           JOptionPane.showMessageDialog(this, "Please check your data", "Invalid information", JOptionPane.ERROR_MESSAGE); 
        }
       
    }//GEN-LAST:event_addBooksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new IssueBookFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(IssueBookFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DateField;
    private javax.swing.JButton addBooksButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField bookCallNumberField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField returnDateField;
    private javax.swing.JTextField studentContactField;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTextField studentNameField;
    // End of variables declaration//GEN-END:variables
}
