/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.AdminSection;
    
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import static java.sql.DriverManager.println;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karim hamdy
 */
public class ReturnBookFrame extends javax.swing.JFrame {

    IssueBook book[] = new IssueBook[100]; 
    Book b1[]=new Book[100];
    Student s1[] = new Student[100];
    int count=0;
    int counts=0;
    int countb=0;
    int y=0;
    /**
     * Creates new form ReturnBookFrame
     */
    public ReturnBookFrame() throws FileNotFoundException {
        initComponents();
        readFilebook();
        readFileStudent();
        readIssueBook();
    }
public void readFilebook() throws FileNotFoundException{
        File f = new File("books.txt");
        Scanner s = new Scanner(f);
        while(s.hasNextLine()){
            String book = s.nextLine();
            String token[]=book.split(",");
                    b1[count]=new Book(token[0],token[1],token[2],token[3],Integer.parseInt(token[4]));
                    count ++;
        }
    }
 public void readFileStudent() throws FileNotFoundException{
        File f = new File("students.txt");
        Scanner s = new Scanner(f);
        while(s.hasNextLine()){
            String student = s.nextLine();
            String token[]=student.split(",");
                   s1[counts] = new Student(token[0],token[1],token[2],token[3],token[4],token[5],token[6],Integer.parseInt(token[7]));
                    counts ++;
        }
    }
 public void readIssueBook() throws FileNotFoundException{
    File f = new File("issue.txt");
        Scanner s = new Scanner(f);
        int x=0,z=0;
        
        while(s.hasNextLine()){
            String student = s.nextLine();
            String token[]=student.split(",");
            for(int i=0;i<count;i++){
                if(b1[i].getCallnumber().equals(token[0]))
                     x=i;
            }
            for(int j=0;j<counts;j++){
                if(s1[j].getId().equals(token[2]))
                    y=j;
                book[countb]=new IssueBook(b1[x],s1[y],token[4],token[5]);
                countb++;
                if((b1[x].getCallnumber().equals(callNumberField.getText()))&&(s1[y].getId().equals(IdField.getText())))
                        y=countb;
                
            }
        }
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        adminFormLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        callNumberField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        IdField = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        passwordLabel1 = new javax.swing.JLabel();
        DateField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminFormLabel.setFont(new java.awt.Font("Myanmar Text", 0, 24)); // NOI18N
        adminFormLabel.setText("Return Book");

        nameLabel.setText("Book Call Number:");

        passwordLabel.setText("Student ID");

        callNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callNumberFieldActionPerformed(evt);
            }
        });

        loginButton.setText("Return Book");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(255, 0, 0));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        passwordLabel1.setText("Date");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(adminFormLabel)
                .addGap(150, 150, 150))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(passwordLabel)
                    .addComponent(passwordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(loginButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(callNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(IdField)
                            .addComponent(DateField, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addComponent(adminFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(callNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(passwordLabel)
                    .addComponent(IdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        for(int m=y;m<countb-1;m++){
            book[m]=book[m+1];
        }
        countb--;
        FileWriter f = null;
        try {
            f = new FileWriter("issue.txt");
        } catch (IOException ex) {
            Logger.getLogger(ReturnBookFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try (PrintWriter pw = new PrintWriter(f)) {
            for(int i=0;i<countb;i++){
                pw.println(book[i].getBook().getCallnumber()+","+book[i].getStudent().getName()+","+book[i].getStudent().getId()+","+book[i].getStudent().getPhonenumber()+","+book[i].getIssuedate()+","+book[i].getReturnDate());
            }
        }
        this.hide();
        new BookReturnedSuccessfullyFrame().setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.hide();
        new LibrarianSectionMenuFrame().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void callNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callNumberFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReturnBookFrame().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ReturnBookFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField DateField;
    private javax.swing.JPasswordField IdField;
    private javax.swing.JLabel adminFormLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField callNumberField;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel passwordLabel1;
    // End of variables declaration//GEN-END:variables
}
